// The release path is one workflow file, and until this test existed nothing
// referenced it. Deleting the step that tags, or the step that creates the
// GitHub Release, left `pnpm run test:release`, `pnpm run release:check` and
// `pnpm run gate:publish-artifacts` all green. Zero tags and zero Releases is
// exactly the state this repository was in when the gap was found, so the
// failure mode is not hypothetical.
//
// What this file protects, and nothing more:
//
//   * an ANNOTATED tag named v<version> is created from the bumped version
//   * that tag is pushed, only in `release` mode
//   * the notes come from scripts/release-notes.mjs, not from a hand-rolled
//     `git log`, and not from the literal string `HEAD~1`, which GitHub cannot
//     resolve and which shipped a dead compare link at the top of the body
//   * the Release is created by a SHA-PINNED softprops/action-gh-release whose
//     body_path is the file those notes were written to
//   * `contents: write` stays scoped to the one release job
//   * no `id-token: write` appears anywhere in the file, because that is the
//     permission npm trusted publishing needs and this workflow states twice
//     that it must never be able to publish
//
// Structure is asserted against the parsed YAML. Shell lines inside `run:`
// blocks are asserted against that step's own script text, so a match cannot
// come from some unrelated part of the file.
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import test from "node:test";
import { load as parseYaml } from "js-yaml";

const root = resolve(import.meta.dirname, "../..");
const workflowPath = join(root, ".github", "workflows", "manual-release.yml");

// The version every downstream name is built from. Written once so the tag
// name, the pushed ref and the Release title can be asserted to agree.
const version = "${{ steps.bump.outputs.version }}";
// The one file the notes are written to and the Release body is read from.
const notesFile = "release-notes.md";
const releaseModeOnly = "inputs.mode == 'release'";

const source = await readFile(workflowPath, "utf8");
const workflow = parseYaml(source);

// The file explains in prose why `id-token: write` is absent, so a raw search
// for it matches the explanation. Comments are stripped before any assertion
// about what the workflow REQUESTS, leaving only lines GitHub Actions acts on.
const executable = source
  .split("\n")
  .map((line) => line.replace(/(^|\s)#.*$/u, "$1"))
  .join("\n");

function job(id) {
  const found = workflow.jobs?.[id];
  assert.ok(found, `manual-release.yml must keep the \`${id}\` job`);
  return found;
}

function step(jobId, name) {
  const found = job(jobId).steps.find((candidate) => candidate.name === name);
  assert.ok(found, `manual-release.yml must keep the \`${name}\` step`);
  return found;
}

// A step's shell script, so `run:` assertions are scoped to the step that owns
// them rather than to the whole file.
function script(jobId, name) {
  const found = step(jobId, name);
  assert.equal(typeof found.run, "string", `\`${name}\` must still be a run step`);
  return found.run;
}

test("the release job tags the cut with an annotated v<version> tag", () => {
  const tagStep = step("release", "Commit and tag the cut");
  // The tag name has to come from the bump, not from a literal, or the tag and
  // the manifests drift apart.
  assert.equal(tagStep.env.VERSION, version);

  const run = tagStep.run;
  assert.match(run, /^\s*git commit -m "chore: release v\$VERSION"$/mu);
  // `-a` is the whole point: a lightweight tag carries no tagger, no date and
  // no message, and `git describe --match "v[0-9]*"` in the step that finds the
  // previous release tag is written against annotated tags.
  assert.match(run, /^\s*git tag -a "v\$VERSION" -m "v\$VERSION"$/mu);
  assert.doesNotMatch(
    run,
    /git tag(?! -a)/u,
    "the release tag must be annotated, so `git tag` must always carry -a",
  );
});

test("the release job pushes that tag, and only in release mode", () => {
  const pushStep = step("release", "Push the commit and the tag");
  // A dry run rehearses the tag locally and throws it away with the runner.
  // Losing this guard would push a real tag off a rehearsal.
  assert.equal(pushStep.if, releaseModeOnly);
  assert.equal(pushStep.env.VERSION, version);

  const run = pushStep.run;
  assert.match(run, /^\s*git push origin "HEAD:\$BRANCH"$/mu);
  // The fully qualified refs/tags/ form, so the push cannot be resolved as a
  // branch of the same name.
  assert.match(run, /^\s*git push origin "refs\/tags\/v\$VERSION"$/mu);
});

test("the release notes are generated by scripts/release-notes.mjs", () => {
  const run = script("release", "Generate the release notes");

  assert.match(run, /^\s*node scripts\/release-notes\.mjs\b/mu);
  assert.match(run, /--from "\$PREVIOUS_TAG"/u);
  assert.match(run, new RegExp(`--out "\\$\\{RUNNER_TEMP\\}/${notesFile}"`, "u"));

  // The range starts at the previous release tag, which the earlier step
  // resolves before the new tag exists.
  const previous = step("release", "Find the previous release tag");
  assert.equal(previous.id, "previous");
  assert.equal(
    step("release", "Generate the release notes").env.PREVIOUS_TAG,
    "${{ steps.previous.outputs.tag }}",
  );

  // Nothing may hand-roll the changelog alongside the generator: the generator
  // refuses to write unless every commit in the range is covered, and a second
  // source of truth would silently bypass that.
  assert.doesNotMatch(run, /git log/u);
});

test("the notes end at a resolved SHA, never the literal HEAD~1", () => {
  const run = script("release", "Generate the release notes");

  // changelogen interpolates whatever `--to` receives straight into the
  // compare URL on the first line of the body. `HEAD~1` is not a ref GitHub
  // can resolve, so passing it verbatim shipped a Release that opened with
  // https://github.com/markless-dev/oxc-tsrx/compare/<sha>...HEAD~1 - a dead
  // link. The range must still END at HEAD~1 (the commit before the release
  // commit), but it has to be resolved to a SHA first.
  assert.doesNotMatch(
    run,
    /--to\s+"?HEAD~1"?/u,
    "passing the literal HEAD~1 as --to produces a dead compare link in the Release body",
  );
  assert.match(
    run,
    /git rev-parse (?:--verify )?"?HEAD~1(?:\^\{commit\})?"?/u,
    "HEAD~1 must be resolved to a concrete SHA before it is passed as --to",
  );
  // And that resolved SHA is what gets passed.
  const resolved = /^\s*(?<name>[A-Z_]+)=\$\(git rev-parse (?:--verify )?"?HEAD~1/mu.exec(run);
  assert.ok(resolved, "the resolved SHA must be captured in a variable");
  assert.match(run, new RegExp(`--to "\\$${resolved.groups.name}"`, "u"));
});

test("the GitHub Release is created by the SHA-pinned action from those notes", () => {
  const releaseStep = step("release", "Create the GitHub Release");

  // Only a real cut publishes.
  assert.equal(releaseStep.if, releaseModeOnly);

  // A floating tag on a third-party action that holds a `contents: write`
  // token is a supply-chain hole. The pin is asserted, not just the name.
  assert.match(
    releaseStep.uses,
    /^softprops\/action-gh-release@[0-9a-f]{40}$/u,
    "the release action must be pinned to a full commit SHA",
  );

  const withBlock = releaseStep.with;
  assert.equal(withBlock.tag_name, `v${version}`);
  assert.equal(withBlock.name, `v${version}`);
  // The body must be the generated notes file, not an inline `body:` and not
  // GitHub's own autogenerated notes.
  assert.equal(withBlock.body_path, `\${{ runner.temp }}/${notesFile}`);
  assert.equal(withBlock.body, undefined);
  assert.equal(withBlock.generate_release_notes, undefined);
  assert.equal(withBlock.draft, false);
  assert.equal(withBlock.prerelease, "${{ inputs.release_type == 'prerelease' }}");
  assert.equal(withBlock.make_latest, "${{ inputs.release_type != 'prerelease' }}");

  // `${{ runner.temp }}` and `${RUNNER_TEMP}` are the same directory written
  // two ways, one in YAML and one in shell. If either side moves, the Release
  // is created with a body_path that does not exist.
  assert.match(
    script("release", "Generate the release notes"),
    new RegExp(`--out "\\$\\{RUNNER_TEMP\\}/${notesFile}"`, "u"),
  );
});

test("contents: write stays scoped to the single release job", () => {
  // Read at the top of the file, the same posture as every other workflow here.
  assert.deepEqual(workflow.permissions, { contents: "read" });

  // Exactly one job, and it is the one that pushes.
  assert.deepEqual(Object.keys(workflow.jobs), ["release"]);
  assert.deepEqual(job("release").permissions, { contents: "write" });
});

test("no id-token: write anywhere, so this workflow cannot publish to npm", () => {
  // manual-release.yml:4 and :51-55 both state this. `id-token: write` is what
  // npm trusted publishing needs, and the two-workflow publish gate exists
  // because 0.1.0 shipped broken. Asserted over every executable line, so a
  // grant at workflow level, at job level, or at any level added later is
  // caught wherever it is written.
  assert.doesNotMatch(
    executable,
    /id-token/iu,
    "manual-release.yml must never request id-token, which is what would let it publish to npm",
  );
  // Structurally too, so a reader can see which blocks were checked.
  for (const permissions of [workflow.permissions, job("release").permissions]) {
    assert.equal(Object.hasOwn(permissions, "id-token"), false);
  }
  // And it must not reach npm by any other route while holding that token.
  assert.doesNotMatch(executable, /npm publish|pnpm publish|NPM_TOKEN/u);
});
