import { defineConfig } from "tsdown";

export default defineConfig({
  cwd: import.meta.dirname,
  entry: [
    "src/canonical-command.ts",
    "src/compat.ts",
    "src/editor-resolution.ts",
    "src/format-cli.ts",
    "src/format-invocation.ts",
    "src/format.ts",
    "src/index.ts",
    "src/lint-cli.ts",
    "src/lint-invocation.ts",
    "src/lint-js-plugins.ts",
    "src/lint-plugins-dev.ts",
    "src/lint-prestart.ts",
    "src/lint.ts",
    "src/native-targets.ts",
    "src/oxlint-lsp-multiplexer.ts",
    "src/package-binary.ts",
    "src/parser.ts",
    "src/process.ts",
    "src/provider-resolve.ts",
    "src/providers-report.ts",
    "src/runtime.ts",
    "src/spawn-command.ts",
    "src/tsrx-transfer.ts",
    "src/bin/oxc-tsrx.ts",
    "src/bin/oxc-tsrx-fmt.ts",
    "src/bin/oxc-tsrx-lint.ts",
    "src/bin/oxc-tsrx-lsp.ts",
    "src/bin/oxfmt.ts",
    "src/bin/oxlint.ts",
  ],
  unbundle: true,
  format: "esm",
  dts: false,
  sourcemap: false,
  deps: {
    neverBundle: true,
  },
  platform: "node",
  target: "node20.19",
  fixedExtension: false,
  outDir: "dist",
  copy: [
    {
      from: [
        "src/canonical-command.d.ts",
        "src/compat.d.ts",
        "src/format.d.ts",
        "src/index.d.ts",
        "src/lint-plugins-dev.d.ts",
        "src/lint.d.ts",
        "src/parser.d.ts",
        "src/provider-resolve.d.ts",
        "src/spawn-command.d.ts",
      ],
      flatten: false,
    },
    {
      from: [
        "../tsrx-core-compat/dist/facade.js",
        "../tsrx-core-compat/dist/index.d.ts",
        "../tsrx-core-compat/dist/index.js",
        "../tsrx-core-compat/dist/style.js",
      ],
      to: "dist/tsrx-core-compat",
    },
    {
      from: [
        "../tsrx-core-compat/dist/types/estree.d.ts",
        "../tsrx-core-compat/dist/types/index.d.ts",
      ],
      to: "dist/tsrx-core-compat/types",
    },
  ],
});
