import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { basename, join, resolve } from "node:path";
import { load as parseYaml } from "js-yaml";

const root = resolve(import.meta.dirname, "..");
const check = process.argv.slice(2).includes("--check");
const unsupported = process.argv.slice(2).filter((argument) => argument !== "--check");
if (unsupported.length > 0) {
  throw new Error(`unsupported option(s): ${unsupported.join(", ")}`);
}

const outputRoot = join(root, "packages/vscode/licenses");
const textRoot = join(outputRoot, "texts");
const bundlePath = join(root, "packages/vscode/dist/extension.bundle.cjs");
const lockfilePath = join(root, "pnpm-lock.yaml");

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function packageLocationsFromBundle(bundle) {
  const packages = new Map();
  const pattern = /^\/\/#region (\S+)/gmu;
  for (const match of bundle.matchAll(pattern)) {
    const modulePath = match[1];
    const marker = "node_modules/";
    const markerIndex = modulePath.lastIndexOf(marker);
    if (markerIndex === -1) continue;
    const prefix = modulePath.slice(0, markerIndex + marker.length);
    const segments = modulePath.slice(markerIndex + marker.length).split("/");
    const name = segments[0].startsWith("@") ? `${segments[0]}/${segments[1]}` : segments[0];
    const installPath = `${prefix}${name}`;
    if (
      installPath.startsWith("/") ||
      installPath.split("/").some((segment) => segment === "." || segment === "..")
    ) {
      throw new Error(
        `bundle region ${modulePath} is not repository-root-relative; rebuild with pnpm run build:editor`,
      );
    }
    packages.set(installPath, { installPath, name });
  }
  if (packages.size === 0) throw new Error("VS Code bundle has no attributable npm regions");
  return [...packages.values()].sort((left, right) =>
    left.installPath.localeCompare(right.installPath),
  );
}

/**
 * Name the shipped license directory for one bundled package.
 *
 * Under pnpm every third-party package is bundled out of the virtual store, so
 * keying the suffix off "is this the plain `node_modules/<name>` path" would
 * give every single entry a hash it does not need. The suffix now appears only
 * where it earns its keep: when one `<name>@<version>` really is bundled from
 * two different locations, which is the only case the directory name has to
 * disambiguate.
 */
function encodedPackageDirectory({ name, version, installPath }, ambiguous) {
  const stem = `${name.replace("/", "__")}@${version}`;
  return ambiguous.has(stem) ? `${stem}-${sha256(installPath).slice(0, 8)}` : stem;
}

function ambiguousStems(entries) {
  const seen = new Map();
  for (const { name, version } of entries) {
    const stem = `${name.replace("/", "__")}@${version}`;
    seen.set(stem, (seen.get(stem) ?? 0) + 1);
  }
  return new Set([...seen].filter(([, count]) => count > 1).map(([stem]) => stem));
}

/**
 * pnpm-lock.yaml keys its `packages` block by `<name>@<version>`, so a scoped
 * name keeps its leading `@` and the separator is the last `@` in the key.
 */
function lockedPackages(lockfileText) {
  const lockfile = parseYaml(lockfileText);
  if (!lockfile || typeof lockfile.packages !== "object") {
    throw new Error("pnpm-lock.yaml has no packages block");
  }
  const locked = new Map();
  for (const [key, entry] of Object.entries(lockfile.packages)) {
    locked.set(key, entry);
  }
  return locked;
}

function renderReport(inventory) {
  const rows = inventory.packages.map(
    (dependency) =>
      `| ${dependency.name} | ${dependency.version} | ${dependency.license} | \`${dependency.licenseTextSha256}\` | \`${dependency.integrity}\` |`,
  );
  return `# VS Code client bundle dependency licenses

This report is generated by \`scripts/generate-vscode-license-inventory.ts\`
from Rolldown's module-region markers, the committed pnpm lockfile, and each
installed package's actual license text. Do not edit it by hand.

The install paths below point into pnpm's virtual store
(\`node_modules/.pnpm/<name>@<version>/node_modules/<name>\`), which is where
Rolldown resolves these modules from. \`lockKey\` is the matching
\`pnpm-lock.yaml\` \`packages\` entry.

- Bundle: \`packages/vscode/dist/extension.bundle.cjs\`
- Bundle SHA-256: \`${inventory.bundleSha256}\`
- pnpm-lock.yaml SHA-256: \`${inventory.lockfileSha256}\`
- Bundled third-party packages: ${inventory.packageCount}

Every listed license/copyright text is shipped byte-exactly below
\`packages/vscode/licenses/texts/\`. The generator fails closed when a new
bundle package or license expression appears.

| Package | Version | License | License-text SHA-256 | npm integrity |
| --- | --- | --- | --- | --- |
${rows.join("\n")}
`;
}

async function legalFilesFor(packageDirectory) {
  const candidates = (await readdir(packageDirectory, { withFileTypes: true }))
    .filter(
      (entry) =>
        entry.isFile() &&
        /^(?:licen[cs]e|copying|notice|copyright)(?:\.|$)/iu.test(entry.name),
    )
    .map((entry) => entry.name)
    .sort();
  if (!candidates.some((name) => /^(?:licen[cs]e|copying)(?:\.|$)/iu.test(name))) {
    throw new Error(
      `${packageDirectory} must expose a top-level license/copying text; found ${candidates.join(", ") || "none"}`,
    );
  }
  return candidates;
}

const [bundle, lockfileText, policyText] = await Promise.all([
  readFile(bundlePath, "utf8"),
  readFile(lockfilePath, "utf8"),
  readFile(join(outputRoot, "allowed-license-expressions.json"), "utf8"),
]);
const locked = lockedPackages(lockfileText);
const policy = JSON.parse(policyText);
const allowed = new Set(policy.allowedExpressions);
const discovered = [];

for (const { installPath, name } of packageLocationsFromBundle(bundle)) {
  const packageDirectory = join(root, ...installPath.split("/"));
  const manifest = JSON.parse(await readFile(join(packageDirectory, "package.json"), "utf8"));
  const lockKey = `${name}@${manifest.version}`;
  const lockEntry = locked.get(lockKey);
  if (!lockEntry) {
    throw new Error(`${lockKey} is not a pnpm-lock.yaml packages entry`);
  }
  // pnpm-lock.yaml does not carry a `license` field the way package-lock.json
  // did, so the license claim is read from the installed manifest and checked
  // against the reviewed allowlist. The integrity below is what binds that
  // manifest to the exact locked tarball.
  if (!manifest.license) {
    throw new Error(`${lockKey} declares no license`);
  }
  if (!allowed.has(manifest.license)) {
    throw new Error(`${lockKey} has unreviewed license: ${manifest.license}`);
  }
  const integrity = lockEntry.resolution?.integrity;
  if (!integrity) throw new Error(`${lockKey} has no locked integrity`);
  discovered.push({
    name,
    version: manifest.version,
    installPath,
    packageDirectory,
    license: manifest.license,
    lockKey,
    integrity,
    legalFiles: await legalFilesFor(packageDirectory),
  });
}

const ambiguous = ambiguousStems(discovered);
const packages = [];
const textOutputs = new Map();

for (const entry of discovered) {
  const directory = encodedPackageDirectory(entry, ambiguous);
  const legalTexts = [];
  for (const legalFile of entry.legalFiles) {
    const legalText = await readFile(join(entry.packageDirectory, legalFile));
    const relativeTextPath = join("texts", directory, legalFile);
    textOutputs.set(relativeTextPath, legalText);
    legalTexts.push({
      path: relativeTextPath.replaceAll("\\", "/"),
      sha256: sha256(legalText),
    });
  }
  const licenseText = legalTexts.find((text) =>
    /\/(?:licen[cs]e|copying)(?:\.|$)/iu.test(text.path),
  );
  packages.push({
    name: entry.name,
    version: entry.version,
    installPath: entry.installPath,
    license: entry.license,
    lockKey: entry.lockKey,
    integrity: entry.integrity,
    licenseTextPath: licenseText.path,
    licenseTextSha256: licenseText.sha256,
    legalTexts,
  });
}

const inventory = {
  schemaVersion: 1,
  generatedBy: "scripts/generate-vscode-license-inventory.ts",
  bundle: "packages/vscode/dist/extension.bundle.cjs",
  bundleSha256: sha256(bundle),
  lockfileSha256: sha256(lockfileText),
  packageCount: packages.length,
  packages,
};
const outputs = new Map([
  ["bundle-dependencies.json", `${JSON.stringify(inventory, null, 2)}\n`],
  ["BUNDLE_DEPENDENCIES.md", renderReport(inventory)],
  ...textOutputs,
]);

if (check) {
  for (const [path, expected] of outputs) {
    const actual = await readFile(join(outputRoot, path)).catch(() => null);
    if (!actual || !Buffer.from(expected).equals(actual)) {
      throw new Error(`${join("packages/vscode/licenses", path)} is stale; run pnpm run licenses:vscode:generate`);
    }
  }
  const expectedDirectories = new Set(
    packages.map((dependency) => encodedPackageDirectory(dependency, ambiguous)),
  );
  const actualDirectories = new Set(await readdir(textRoot).catch(() => []));
  assertSameEntries(actualDirectories, expectedDirectories, "generated VS Code license directories");
} else {
  await rm(textRoot, { recursive: true, force: true });
  for (const [path, contents] of outputs) {
    const absolute = join(outputRoot, path);
    await mkdir(join(absolute, ".."), { recursive: true });
    await writeFile(absolute, contents);
  }
}

function assertSameEntries(actual, expected, label) {
  const extra = [...actual].filter((entry) => !expected.has(entry));
  const missing = [...expected].filter((entry) => !actual.has(entry));
  if (extra.length > 0 || missing.length > 0) {
    throw new Error(`${label} drifted; extra=${extra.join(",")} missing=${missing.join(",")}`);
  }
}

process.stdout.write(
  `${check ? "verified" : "generated"} ${packages.length} bundled VS Code dependency licenses\n`,
);
