//! The fixed `ESTree` key vocabulary the binary format encodes as a small id instead of a string.

pub(super) const BINARY_COMMON_KEY_FLAG: u32 = 1 << 31;

pub(super) fn common_key_id(key: &str) -> Option<u32> {
    Some(match key {
        "body" => 0,
        "end" => 1,
        "hashbang" => 2,
        "sourceType" => 3,
        "start" => 4,
        "type" => 5,
        "async" => 6,
        "attributes" => 7,
        "declaration" => 8,
        "expression" => 9,
        "generator" => 10,
        "id" => 11,
        "metadata" => 12,
        "name" => 13,
        "params" => 14,
        "path" => 15,
        "render" => 16,
        "children" => 17,
        "closingElement" => 18,
        "openingElement" => 19,
        "selfClosing" => 20,
        "value" => 21,
        "raw" => 22,
        "source" => 23,
        "specifiers" => 24,
        "kind" => 25,
        "local" => 26,
        "phase" => 27,
        "optional" => 28,
        "imported" => 29,
        "declarations" => 30,
        "init" => 31,
        "arguments" => 32,
        "callee" => 33,
        "computed" => 34,
        "key" => 35,
        "operator" => 36,
        "method" => 37,
        "properties" => 38,
        "shorthand" => 39,
        "left" => 40,
        "right" => 41,
        "object" => 42,
        "property" => 43,
        "argument" => 44,
        "statementType" => 45,
        "prefix" => 46,
        "consequent" => 47,
        "test" => 48,
        "alternate" => 49,
        "block" => 50,
        "finalizer" => 51,
        "handler" => 52,
        "param" => 53,
        "pending" => 54,
        "resetParam" => 55,
        "await" => 56,
        "empty" => 57,
        "index" => 58,
        "elements" => 59,
        "typeAnnotation" => 60,
        "accessibility" => 61,
        "declare" => 62,
        "members" => 63,
        _ => return None,
    })
}

pub(super) fn common_key(id: u32) -> Option<&'static str> {
    const KEYS: [&str; 64] = [
        "body",
        "end",
        "hashbang",
        "sourceType",
        "start",
        "type",
        "async",
        "attributes",
        "declaration",
        "expression",
        "generator",
        "id",
        "metadata",
        "name",
        "params",
        "path",
        "render",
        "children",
        "closingElement",
        "openingElement",
        "selfClosing",
        "value",
        "raw",
        "source",
        "specifiers",
        "kind",
        "local",
        "phase",
        "optional",
        "imported",
        "declarations",
        "init",
        "arguments",
        "callee",
        "computed",
        "key",
        "operator",
        "method",
        "properties",
        "shorthand",
        "left",
        "right",
        "object",
        "property",
        "argument",
        "statementType",
        "prefix",
        "consequent",
        "test",
        "alternate",
        "block",
        "finalizer",
        "handler",
        "param",
        "pending",
        "resetParam",
        "await",
        "empty",
        "index",
        "elements",
        "typeAnnotation",
        "accessibility",
        "declare",
        "members",
    ];
    KEYS.get(usize::try_from(id).ok()?).copied()
}
